---
- name: Disks | Install smartd
  ansible.builtin.apt:
    update_cache: true # yamllint disable-line rule:truthy
    pkg:
      - smartmontools
    stats: present

- name: Disks | Configure smartd
  ansible.builtin.template:
    src: smartd.conf.j2
    dest: /etc/smartd.conf
    mode: "0644"

- name: Disks | Restart smartd services
  ansible.builtin.systemd:
    name: smartd
    daemon_reload: true
    enabled: true
    state: restarted
