---
- name: Grub | Check if grub exists
  ansible.builtin.stat:
    path: /etc/default/grub
    register: grub_result

- name: Grub | Check if apparmor are disabled
  ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | grep -c "apparmor=0"
  register: apparmor_status
  ignore_errors: true

- name: Grub | Check if mitigations are disabled
  ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | grep -c "mitigations=off"
  register: mitigations_status
  ignore_errors: true

- name: Grub | Disabled apparmor
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ option }}={{ value }}\2'
  vars:
    option: apparmor
    value: 0
  when:
    - grub_result.stat.exists
    - apparmor_status.stdout == "0"

- name: Grub | Disabled mitigations
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ option }}={{ value }}\2'
  vars:
    option: mitigations
    value: "off"
  when:
    - grub_result.stat.exists
    - mitigations_status.stdout == "0"

- name: Grub | Run grup-mkconfig
  ansible.builtin.command: update-grub
  when:
    - grub_result.stat.exists
    - apparmor_status.stdout == "0"
    - mitigations_status.stdout == "0"
