---
- name: Locale | Set Timezone
  community.general.timezone:
    name: "{{ timezone | default('Asia/Jakarta') }}"

- name: Locale | Copy timesyncd config
  ansible.builtin.copy:
  mode: "0644"
  content: |
    [Time]
    NTP={{ ntp_servers.primary | default("times.google.com") | join(" ") }}
    FallbackNTP={{ ntp_servers.fallback | join(" ") }}
  dest: /etc/systemd/timesyncd.conf
  when:
    - ntp_servers.primary is defined
    - ntp_servers.primary is iterable
    - ntp_servers.primary | length > 0
    - ntp_servers.fallback is defined
    - ntp_servers.fallback is iterable
    - ntp_servers.fallback | length > 0

- name: Locale | Start systemd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Locale | Restart systemd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    daemon_reload: true
    enabled: true
    state: restarted

- name: Locale | Run timedatectl status
  ansible.builtin.command: /usr/bin/timedatectl show
  changed_when: false
  check_mode: false
  register: timedatectl_result
