---
# Define the host as control plane nodes
k3s_control_node: true

# S3 snapshot settings for etcd
# k3s_etcd_snapshot_schedule_cron: "0 */4 * * *"
# k3s_etcd_snapshot_retention: 24
# k3s_etcd_s3_endpoint: "s3.{{ domain }}"
# k3s_etcd_s3_bucket: k3s
# k3s_etcd_s3: true

k3s_server:
  cluster-cidr: 10.132.0.0/16
  disable: ["flannel", "local-storage", "metrics-server", "servicelb", "traefik"]
  disable-cloud-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  docker: false
  etcd-disable-snapshots: true
  etcd-expose-metrics: true
  flannel-backend: "none" # quote
  kube-controller-manager-arg: ["bind-address=0.0.0.0"]
  kube-scheduler-arg: ["bind-address=0.0.0.0"]
  kubelet-arg: ["image-gc-low-threshold=50", "image-gc-high-threshold=55"]
  node-ip: "{{ ansible_host }}"
  secrets-encryption: true
  service-cidr: 10.133.0.0/16
  tls-san: ["{{ k3s_registration_address }}", "infra.monosense.dev", "infra"]
  write-kubeconfig-mode: "0644" # quote