---
- name: avahi | install avahi service
  ansible.builtin.apt:
    update_cache: yes # yamllint disable-line rule:truthy
    pkg:
      - avahi-daemon
    state: present

- name: avahi | restart avahi service
  ansible.builtin.systemd:
    name: avahi-daemon
    daemon_reload: true
    enabled: true
    state: restarted