---
# basic helm values to generate ansible templates
autoDirectNodeRoutes: true
k8sServiceHost: "infra.${SECRET_DOMAIN}"
k8sServicePort: 6443
nativeRoutingCIDR: 10.42.0.0/16
rollOutCiliumPods: true
tunnel: disabled
kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
containerRuntime:
  integration: containerd
ipam:
  mode: "kubernetes"
operator:
  rollOutPods: true
  replicas: 1