---
all:
  children:
    master-nodes:
      hosts:
        k8s-0-nas:
          ansible_host: 172.16.11.1
          ansible_user: monosense
    worker-nodes:
      hosts:
    storage-nodes:
      hosts:
        k8s-0-nas: