---
- name: Cluster Prepare
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Base OS | Configure Locale
      ansible.builtin.include_tasks: tasks/os/os-locale.yaml

    - name: Base OS | Configure and Install Packages
      ansible.builtin.include_tasks: tasks/os/os-packages.yaml

    - name: Base OS | Configure Kernel
      ansible.builtin.include_tasks: tasks/os/os-kernel.yaml

    - name: Base OS | Configure Filesystem
      ansible.builtin.include_tasks: tasks/os/os-filesystem.yaml

    - name: Base OS | Configure SMARTD
      ansible.builtin.include_tasks: tasks/os/os-disks.yaml

    - name: Base OS | Configure GRUB
      ansible.builtin.include_tasks: tasks/os/os-grub.yaml

    - name: Base OS | Configure Unattended Upgrades
      ansible.builtin.include_tasks: tasks/os/os-upgrade.yaml

    - name: Base OS | Configure Group
      ansible.builtin.include_tasks: tasks/os/os-groups.yaml

    - name: Base OS | Configure Users
      ansible.builtin.include_tasks: tasks/os/os-users.yaml
